bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost dbname=restapi_dev user=postgres password=myPassword sslmode=disable"
db_driver = "postgres"
session_key = "b45bdfhsdgfuyg4bdysfubsadufefhksbaiugb23iurfg23fgw893oiht0ghsdifduifi"